name: smart_parking_university_mobile
description: Smart Parking University mobile app
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.0+1
  http: ^1.2.2
  image: ^4.2.0
  image_picker: ^1.1.2
  mqtt_client: ^10.5.1
  shared_preferences: ^2.3.3
  google_mlkit_face_detection: ^0.13.1
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  wakelock_plus: ^1.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/ucepark_logo.png
    - assets/images/logo_mark.png
    - assets/images/logo_lockup.png
